### ISSUE TITLE
Usage of 

### ISSUE THREAD

**Issue by simonmeggle** [contributor-assistant/github-action#113]
**Describe the bug**
It is not possible to link to the CLA document if you use a custom `custom-notsigned-prcomment` in `cla.yml`. 

**To Reproduce**
Add this line to `cla.yml`: 

    custom-notsigned-prcomment: '<br/>Thank you for your Pull Request, we really appreciate it!<br/>We kindly ask that you to sign our [Contributor License Agreement](${input.getPathToDocument()}) before....  ... .... '

But obviously, `getPathToDocument` cannot be called within a custom message. 

**Expected behavior**
I expect to see the Hyperlink to the documentation. 

=> How can I use a custom `custom-notsigned-prcomment` and still insert the CLA link dynamically?

**Comment by ronald-jaepel** [comment]
Hey, 

we got this working by turning it into an environment variable.
The following works for us:

```yaml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          [...]
          PATH_TO_CLA: 'https://github.com/jubiotech/detl/blob/main/CLA.md'
        with:
          path-to-signatures: [...]
          path-to-document: $PATH_TO_CLA
          [...]
          custom-notsigned-prcomment: >
              Like many open-source projects we ask that you sign our [Contributor License Agreement]($PATH_TO_CLA) before we can accept your contribution.
          [...]

```
