### ISSUE TITLE
[BUG] Action is fialing with graphql error

### ISSUE THREAD

**Issue by rokups** [contributor-assistant/github-action#130]
CLA workflow fails with a following error:
> Error: graphql call to get the committers details failed: GraphqlError: Resource not accessible by integration

My workflow file:
```yml
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: '.github/signatures/version1/cla.json'
          path-to-document: 'https://github.com/rokups/charting_app/blob/master/.github/CLA.md'
          branch: 'master'
          allowlist: rokups
          lock-pullrequest-aftermerge: false
```

![image](https://user-images.githubusercontent.com/19151258/218303862-aaddfcdc-88bd-43b7-a773-744aa9e03f6c.png)

I did try with and without `PERSONAL_ACCESS_TOKEN`. Repository is private.

**Comment by ibakshay** [comment]
Hi @rokups,
I will look into your issue today and will keep you posted :)

**Comment by ibakshay** [comment]
Hi @rokups,
Looks like you have configured Github Actions workflow permissions in your private repository to "read repository contents and packages permissions". So then, you need to manually specify permissions in the CLA workflow file like below. 
![Screenshot 2023-02-16 at 22 55 25](https://user-images.githubusercontent.com/33329946/219495783-abdd3f16-8297-4e9e-ba19-e31e52765372.png)
Feel free to create a PR and mention about adding this permission explicitly in this repository's README if the below workflow file works for you :) 

```yaml
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: '.github/signatures/version1/cla.json'
          path-to-document: 'https://github.com/rokups/charting_app/blob/master/.github/CLA.md'
          branch: 'master'
          allowlist: rokups
          lock-pullrequest-aftermerge: false
```
For more information, [please refer this link](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions)
