### ISSUE TITLE
[BUG] How to use this action on a protected branch?

### ISSUE THREAD

**Issue by sumanth-lingappa** [contributor-assistant/github-action#150]
**Describe the bug**
I have setup a CLA for our repo.
Earlier, the CLA used to work as expected. Refer [HERE](https://github.com/netscaler/ansible-collection-netscaleradc/pull/382)

Now, it started giving [this comment](https://github.com/netscaler/ansible-collection-netscaleradc/pull/407#issuecomment-2051284487) even for a cla-signed user!

**To Reproduce**
My CLA workflow is [HERE](https://github.com/netscaler/ansible-collection-netscaleradc/blob/2f4808207723ef7c71a4cf4324ea25349d70bf30/.github/workflows/cla.yml)

```yml
---
name: CLA Assistant
on:
  # issue_comment:
  #   types: [created] # commented as we do not need CLA for raising issues
  pull_request_target:
    types: [opened, closed, synchronize]
# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby
          sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: https://gist.githubusercontent.com/konstantika/217986f1a636d42bf4fcf3680a11a5b8/raw/808a16c96ac10ac4ce703525faf586c86f574c02/csg_cla_ansible.txt
          # branch should not be protected
          branch: "main"
          allowlist: bot*
          # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          #remote-organization-name: enter the remote organization name where the signatures should be stored (Default is storing the signatures in the same repository)
          #remote-repository-name: enter the  remote repository name where the signatures should be stored (Default is storing the signatures in the same repository)
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          #custom-notsigned-prcomment: 'pull request comment with Introductory message to ask new contributors to sign'
          #custom-pr-sign-comment: 'The signature to be committed in order to sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
          #use-dco-flag: true - If you are using DCO instead of CLA
```

I have also observed that, there are two workflows run for CLA
- license/cla -- which gets successful
-  CLA Assistant / CLAAssistant (pull_request_target) -- which fails

![image](https://github.com/contributor-assistant/github-action/assets/42572246/1e7f5b61-9132-4ec3-9f9a-7cbcfe51e6a7)

![image](https://github.com/contributor-assistant/github-action/assets/42572246/a47c2eda-a680-4c52-b3b5-e307fcc8cc94)

**Expected behavior**
The CLA should work as [before](https://github.com/netscaler/ansible-collection-netscaleradc/pull/382)

**Screenshots**
![image](https://github.com/contributor-assistant/github-action/assets/42572246/321b7083-90c1-4820-b025-2bc42e9ebf64)
