### ISSUE TITLE
[BUG] Path to document is wrong in comment

### ISSUE THREAD

**Issue by cskiwi** [contributor-assistant/github-action#67]
**Describe the bug**
The comment made on the PR includes a link to the CLA, But this was empty.
This is however on a private repo (for now) so that could be the reason.

**To Reproduce**
config:

```yaml
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Alpha Release
        uses: cla-assistant/github-action@v2.0.1-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/<hidden>/core/blob/main/CLA.md"
          branch: "main"
          allowlist: bot*
          create-file-commit-message: 'chore(docs): Creating file for storing CLA Signatures'
          signed-commit-message: 'chore: $contributorName has signed the CLA in #$pullRequestNo'
```

**Expected behavior**
The link included in the commit message
