### ISSUE TITLE
[BUG] HttpError: Not Found on re-running the workflow 

### ISSUE THREAD

**Issue by sebastianpiq** [contributor-assistant/github-action#99]
**Describe the bug**
After signing "I have read the CLA Document and I hereby sign the CLA" as a comment. The CLAssistant Action saves the user sign in the JSON but when it tries to re-run the last failed action it returns a HttpError: Not Found

The cla.yml that I am using:

```
name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          remote-organization-name: 'sebap'
          remote-repository-name: 'clas'
          path-to-signatures: 'test-signature/signatures.json'
          path-to-document: 'https://github.com/sebap/sebap-cli/blob/main/LICENSE'
          branch: 'main'
          allowlist: bot*
```

**To Reproduce**
- Create a Pull Request and wait for the failure of the CLAssistant Action
- Left "I have read the CLA Document and I hereby sign the CLA" as a comment to sings
- Wait again for the CLAssistant Action and see the error in Annotations "Error occurred when re-running the workflow: HttpError: Not Found".

**Expected behavior**
The CLAssistant Action re-run successfully last failed workflow after signing

**Screenshots**
![image](https://user-images.githubusercontent.com/89274285/152538143-e43509d0-fd52-4b24-ad03-b59e99f0e88c.png)
